name: cooquoi
services:
  cooquoi_db:
    image: postgis/postgis:16-3.4
    container_name: cooquoi
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME:-appinstance}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-azerty}
      POSTGRES_DB: ${DB_POSTGRES_DB_NAME:-cooquoi}
    volumes:
      - cooquoi_db_data:/var/lib/postgresql/data
      - ../../scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro

  cooquoi_api:
    image: cooquoi-api:latest
    container_name: cooquoi-api
    restart: unless-stopped
    profiles: [api, all]
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://${DB_POSTGRES_USERNAME:-appinstance}:${DB_POSTGRES_PASSWORD:-azerty}@cooquoi_db:5432/${DB_POSTGRES_DB_NAME:-cooquoi}
      DATABASE_SEEDING_ENABLED: "false"
    depends_on:
      - cooquoi_db

  cooquoi_webapp:
    image: cooquoi-webapp:latest
    container_name: cooquoi-webapp
    restart: unless-stopped
    profiles: [webapp, all]
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://cooquoi_api:3000
    depends_on:
      - cooquoi_api

volumes:
  cooquoi_db_data:
