packages:
  - libs/*
  - apps/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - nx
  - sharp
  - unrs-resolver
