import { Topbar } from "@/components/features/top-bar";
import { Roboto } from "next/font/google";
import "./global.css";

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["400", "500", "700"],
	display: "swap",
	variable: "--font-sans",
});

export const metadata = {
	title: "Welcome to cooquoi-webapp",
	description: "Generated by create-nx-workspace",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={roboto.variable}>
			<body className="font-sans">
				<Topbar />
				{children}
			</body>
		</html>
	);
}
