import { Topbar } from "@/components/features/top-bar";
import "./global.css";

export const metadata = {
	title: "Welcome to cooquoi-webapp",
	description: "Generated by create-nx-workspace",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Topbar />
				{children}
			</body>
		</html>
	);
}
